from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT
UPLOAD_DIR = DATA_DIR / "uploads"
REPORT_DIR = DATA_DIR / "reports"
DB_PATH = DATA_DIR / "tender_diagnosis.db"
DATABASE_URL = f"sqlite+aiosqlite:///{DB_PATH}"
# 招标/标书常见 1–2GB；默认单文件上限 2GB
MAX_UPLOAD_BYTES = 2 * 1024 * 1024 * 1024
ALLOWED_EXTENSIONS = {".pdf", ".docx"}
MOCK_ITEM_DELAY_SECONDS = 0.8
# Kept for MockInterpretationAgent unit tests only; production uses Agent OS.
MOCK_INTERPRET_DELAY_SECONDS = 0.5
MOCK_BATCH_DIAGNOSIS_DELAY_SECONDS = 0.5
# Unused by scheduler (always AgentOSInterpretationAgent); kept for compatibility.
INTERPRETATION_AGENT = "agent_os"
INTERPRETATION_AGENT_URL = ""
CHECKLIST_AGENT = "agent_os"
CHECKLIST_AGENT_VERSION = "1"
CHECKLIST_SCHEMA_VERSION = "1"
CHECKLIST_SINGLE_PASS_TOKENS = 24_000
CHECKLIST_CHUNK_TOKENS = 12_000
CHECKLIST_CHUNK_OVERLAP_TOKENS = 500
CHECKLIST_MAX_ITEMS_PER_CATEGORY = 20
CHECKLIST_PARSE_POLL_SECONDS = 0.1
BATCH_DIAGNOSIS_INDEX_WAIT_TIMEOUT_SECONDS = 7200.0
BATCH_DIAGNOSIS_INDEX_POLL_SECONDS = 2.0
RETRIEVAL_PROVIDER = "workspace"  # workspace | mock
INDEX_TAG_MIN_CONFIDENCE = 0.5
PRECISE_SEARCH_TOP_K = 20
PRECISE_SEARCH_RECALL_PER_CHANNEL = 40
PRECISE_SEARCH_CHANNEL_WEIGHT_VECTOR = 0.5
PRECISE_SEARCH_CHANNEL_WEIGHT_FTS = 0.3
PRECISE_SEARCH_CHANNEL_WEIGHT_WIKI = 0.2
EMBEDDING_MODEL_PATH = ""  # local path; empty → hash-embedding fallback for tests
EMBEDDING_DIM = 384
OCR_ENABLED = True
OCR_MIN_CHARS_PER_PAGE = 40